#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-procps

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_procps.tgz

echo "+==============+"
echo "| procps-2.0.7 |"
echo "+==============+"
cd $TMP
tar xzvf $CWD/procps-2.0.7.tar.gz
cd procps-2.0.7
mkdir -p $PKG/usr/doc/procps-2.0.7
cp -a BUGS COPYING COPYING.LIB INSTALL NEWS TODO $PKG/usr/doc/procps-2.0.7
chown root.root $PKG/usr/doc/procps-2.0.7/*
chmod 644 $PKG/usr/doc/procps-2.0.7/*
# Fix a couple annoying things:
zcat $CWD/procps.top-nobright.diff.gz | patch -p0
zcat $CWD/procps.nowarning.diff.gz | patch -p0
zcat $CWD/procps.ksyms.nowhine.diff.gz | patch -p0
zcat $CWD/procps.digiboard.diff.gz | patch -p0
zcat $CWD/procps.locale.diff.gz | patch -p1
make
strip kill ps/ps proc/libproc.so.2.0.7 free oldps tload top uptime vmstat \
      w watch
cat kill > $PKG/bin/kill
cat ps/ps> $PKG/bin/ps
cat proc/libproc.so.2.0.7 > $PKG/lib/libproc.so.2.0.7
cat XConsole > $PKG/usr/X11R6/bin/XConsole
cat free > $PKG/bin/free
cat oldps > $PKG/usr/bin/oldps
cat tload > $PKG/usr/bin/tload
cat top > $PKG/usr/bin/top
cat uptime > $PKG/usr/bin/uptime
cat vmstat > $PKG/usr/bin/vmstat
cat w > $PKG/usr/bin/w
cat watch > $PKG/usr/bin/watch
cp ps/ps.1 .
for page in free.1 kill.1 oldps.1 ps.1 skill.1 snice.1 tload.1 \
  top.1 uptime.1 w.1 watch.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
for page in vmstat.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done

echo "+=============+"
echo "| psmisc-20.1 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/psmisc-20.1.tar.gz
cd psmisc-20.1
./configure --prefix=/usr
mkdir -p $PKG/usr/doc/psmisc-20.1
cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README $PKG/usr/doc/psmisc-20.1
chmod 644 $PKG/usr/doc/psmisc-20.1/*
chown root.root $PKG/usr/doc/psmisc-20.1/*
make
( cd src
  strip fuser pstree killall
  cat fuser > $PKG/usr/bin/fuser
  cat pstree > $PKG/usr/bin/pstree
  cat killall > $PKG/bin/killall
  cd ../doc
  for page in fuser.1 killall.1 pstree.1 ; do
    cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
  done
)

echo "+=============+"
echo "| procinfo-18 |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/procinfo-18.tar.gz
cd procinfo-18
mkdir -p $PKG/usr/doc/procinfo-18
cp -a CHANGES README $PKG/usr/doc/procinfo-18
chmod 644 $PKG/usr/doc/procinfo-18/*
chown root.root $PKG/usr/doc/procinfo-18/*
make
strip procinfo
cat procinfo > $PKG/usr/bin/procinfo
cat lsdev.pl > $PKG/usr/bin/lsdev
cat socklist.pl > $PKG/usr/bin/socklist
for page in procinfo.8 lsdev.8 socklist.8 ; do
  cat $page | gzip -9c > $PKG/usr/man/man8/$page.gz
done

# Build the package:
cd $PKG
tar czvf $TMP/procps.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/procps-2.0.7
  rm -rf $TMP/procinfo-18
  rm -rf $TMP/psmisc-20.1
  rm -rf $PKG
fi
