#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-bonobo

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/bonobo-1.0.4.tar.gz
cd bonobo-1.0.4
CFLAGS=-O2 ./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            sparc-slackware-linux
make
make DESTDIR=$PKG install
mkdir -p $PKG/usr/doc/bonobo-1.0.4
cp -a ABOUT-NLS AUTHORS COPYING COPYING.LIB ChangeLog INSTALL NEWS README \
  TODO $PKG/usr/doc/bonobo-1.0.4
chmod 644 $PKG/usr/doc/bonobo-1.0.4/*
chown root.root $PKG/usr/doc/bonobo-1.0.4/*

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/bonobo.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/bonobo-1.0.4
  rm -rf $PKG
fi
