#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gtm

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gtm-0.4.9.tar.gz
cd gtm-0.4.9
CFLAGS=-O2 ./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            --localstatedir=/var/lib \
            sparc-slackware-linux
make
make DESTDIR=$PKG install
gzip $PKG/opt/gnome/man/man1/*
mkdir -p $PKG/usr/doc/gtm-0.4.9
cp -a ABOUT-NLS AUTHORS BUGS COPYING ChangeLog INSTALL NEWS README TODO \
  $PKG/usr/doc/gtm-0.4.9
chmod 644 $PKG/usr/doc/gtm-0.4.9/*
chown root.root $PKG/usr/doc/gtm-0.4.9/*

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gtm.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gtm-0.4.9
  rm -rf $PKG
fi
