#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gzip

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_gzip.tar.gz

echo "+=============+"
echo "| gzip-1.2.4a |"
echo "+=============+"
cd $TMP
tar xzvf $CWD/gzip-1.2.4a.tar.gz
cd gzip-1.2.4a
./configure --prefix=/usr
make CFLAGS=-O2 LDFLAGS=-s
cat gzip > $PKG/bin/gzip
for page in gzexe.1 gzip.1 zdiff.1 zforce.1 zgrep.1 zmore.1 znew.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
mkdir -p $PKG/usr/info
cat gzip.info | gzip -9c > $PKG/usr/info/gzip.info.gz
mkdir -p $PKG/usr/doc/gzip-1.2.4a
cp -a COPYING ChangeLog INSTALL NEWS README THANKS TODO algorithm.doc $PKG/usr/doc/gzip-1.2.4a/

# Build the package:
cd $PKG
tar czvf $TMP/gzip.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gzip-1.2.4
  rm -rf $PKG
fi
