#!/bin/sh
CWD=`pwd` 
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-libgtop

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/libgtop-1.0.12.tar.gz
cd libgtop-1.0.12
CFLAGS=-O2 ./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            sparc-slackware-linux
make
make DESTDIR=$PKG install
mkdir -p $PKG/usr/doc/libgtop-1.0.12
cp -a ABOUT-NLS AUTHORS COPYING ChangeLog INSTALL LIBGTOP-VERSION NEWS \
   README RELNOTES-0.25 RELNOTES-1.0 RELNOTES-1.0.x \
   $PKG/usr/doc/libgtop-1.0.12
chown -R root.root $PKG/usr/doc/libgtop-1.0.12

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/libgtop.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/libgtop-1.0.12
  rm -rf $PKG
fi
