#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-floppy
mkdir -p $PKG
cd $TMP

tar xzvf $CWD/fdutils-5.4.tar.gz
cd fdutils-5.4
zcat $CWD/fdutils-5.4-20010112.diff.gz | patch -p1 --verbose --backup --suffix=.orig
zcat $CWD/fdutils.mediaprm.diff.gz | patch -p1 --verbose --backup --suffix=.orig
./configure sparc-slackware-linux --prefix=/usr --sysconfdir=/etc
make 
make install prefix=$PKG/usr 
mkdir -p $PKG/usr/doc/fdutils-5.4
cp -a COPYING CREDITS Changelog INSTALL doc/FAQ.html doc/README \
  $PKG/usr/doc/fdutils-5.4
chown root.root $PKG/usr/doc/fdutils-5.4/*
chmod 644 $PKG/usr/doc/fdutils-5.4/*
cd $TMP
tar xzvf $CWD/mtools-3.9.7.tar.gz
cd mtools-3.9.7
zcat $CWD/mtools-3.9.7-20010325d.diff.gz | patch -p1 --verbose --backup --suffix=.orig
./configure sparc-slackware-linux --prefix=/usr --sysconfdir=/etc
mkdir -p $PKG/etc
cat $CWD/mtools.conf > $PKG/etc/mtools.conf
make 
make install prefix=$PKG/usr
mkdir -p $PKG/usr/doc/mtools-3.9.7
cp -a COPYING Changelog INSTALL README Release.notes TODO \
  $PKG/usr/doc/mtools-3.9.7
chown root.root $PKG/usr/doc/mtools-3.9.7/*
chmod 644 $PKG/usr/doc/mtools-3.9.7/*
# These are obsolete and/or cruft:
rm -f $PKG/usr/bin/MAKEFLOPPIES $PKG/usr/bin/lz $PKG/usr/bin/mcheck $PKG/usr/bin/mcomp \
      $PKG/usr/bin/mxtar $PKG/usr/bin/tgz $PKG/usr/bin/uz $PKG/usr/man/man1/makefloppies.1

cd $PKG
echo "y
n" | makepkg $TMP/floppy.tgz
