#!/bin/sh
# Set initial variables:
#
# Building this package requires the audiofil.tgz package to be installed

CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-mp3

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_mp3.tar.gz

echo "+===========+"
echo "| amp-0.7.6 |"
echo "+===========+"
cd $TMP
tar xzvf $CWD/amp-0.7.6.tar.gz
cd amp-0.7.6
zcat $CWD/amp-0.7.6-sparc-linux.diff.gz | patch -p1 --verbose
./configure --prefix=/usr sparc-slackware-linux
make
strip amp

cat amp > $PKG/usr/bin/amp
cat amp.1 | gzip -9c > $PKG/usr/man/man1/amp.1.gz
mkdir -p $PKG/usr/doc/amp-0.7.6
cp -a BUGS CHANGES README TODO doc/jukebox.txt doc/layer2.txt doc/linuxrealtime.txt doc/BeOS.txt $PKG/usr/doc/amp-0.7.6
chown -R root.root $PKG/usr/doc/amp-0.7.6
chmod 644 $PKG/usr/doc/amp-0.7.6/*

echo "+==============+"
echo "| mpg123-0.59r |"
echo "+==============+"
cd $TMP
tar xzvf $CWD/mpg123-0.59r.tar.gz
cd mpg123-0.59r
zcat $CWD/mpg123-0.59r.sparc.diff.gz | patch -p1

if [ ! -f /opt/gnome/include/audiofile.h ] ; then
  echo You must have the audiofil.tgz package installed
  exit
else
  ln -sf /opt/gnome/include/audiofile.h /usr/include
  ln -sf /opt/gnome/include/aupvlist.h /usr/include
fi

mkdir -p $PKG/usr/doc/mpg123-0.59r
cp -a BENCHMARKING BUGS CHANGES COPYING INSTALL JUKEBOX README README.remote TODO $PKG/usr/doc/mpg123-0.59r
chown -R root.root $PKG/usr/doc/mpg123-0.59r
chmod 644 $PKG/usr/doc/mpg123-0.59r/*
make linux-sparc CFLAGS=-I/opt/gnome/include
cat mpg123 > $PKG/usr/bin/mpg123
cat mpg123.1 | gzip -9c > $PKG/usr/man/man1/mpg123.1.gz

# Build the package:
cd $PKG
tar czvf $TMP/mp3.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
A  rm -rf $TMP/amp-0.7.6
  rm -rf $TMP/mpg123-0.59r
  rm -rf $PKG
fi
