#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gnomemm

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gnomemm-1.1.16.tar.gz
cd gnomemm-1.1.16
./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            sparc-slackware-linux
make CFLAGS=-O2
make CFLAGS=-O2 DESTDIR=$PKG install
mkdir -p $PKG/usr/doc/gnomemm-1.1.16
cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
   $PKG/usr/doc/gnomemm-1.1.16
chown -R root.root $PKG/usr/doc/gnomemm-1.1.16

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gnomemm.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnomemm-1.1.16
  rm -rf $PKG
fi
