#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-seejpeg

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_seejpeg.tar.gz

echo "+==============+"
echo "| seejpeg-1.10 |"
echo "+==============+"
cd $TMP
tar xzvf $CWD/seejpeg-1.10.tgz
cd seejpeg-1.10
zcat $CWD/seejpeg-1.10.diff.gz | patch -p1
rm -rf jpeglib
tar xzvf $CWD/libjpeg-6a.tar.gz
( cd libjpeg-6a ; ./configure ; make )
ln -sf libjpeg-6a jpeglib
make seejpeg
strip seejpeg
cat seejpeg > $PKG/usr/bin/seejpeg
cat seejpeg.1 | gzip -9c > $PKG/usr/man/man1/seejpeg.1.gz
mkdir -p $PKG/usr/doc/seejpeg-1.10
cp -a CHANGELOG README $PKG/usr/doc/seejpeg-1.10
chown root.root $PKG/usr/doc/seejpeg-1.10/*
chmod 644 $PKG/usr/doc/seejpeg-1.10/*

# Build the package:
cd $PKG
tar czvf $TMP/seejpeg.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/seejpeg-1.10
  rm -rf $PKG
fi
