#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-cpio

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_cpio.tar.gz

echo "+============+"
echo "| cpio-2.4.2 |"
echo "+============+"
cd $TMP
tar xzvf $CWD/cpio-2.4.2.tar.gz
cd cpio-2.4.2
zcat $CWD/cpio-2.4.2.diff.gz | patch -p1
./configure --prefix=/usr
make CFLAGS=-O2 LDFLAGS=-s
cat cpio > $PKG/bin/cpio
cat mt > $PKG/bin/mt-GNU
for page in cpio.1 mt.1 ; do
  cat $page | gzip -9c > $PKG/usr/man/man1/$page.gz
done
cat cpio.info | gzip -9c > $PKG/usr/info/cpio.info.gz

# Build the package:
cd $PKG
tar czvf $TMP/cpio.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/cpio-2.4.2
  rm -rf $PKG
fi
