#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-etc

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_etc.tar.gz
cp -a $CWD/termcap-BSD.gz etc/termcap-BSD.gz
gzip -d etc/termcap-BSD.gz
chown root.root etc/termcap-BSD
chmod 644 etc/termcap-BSD
zcat $CWD/nsswitch.conf.gz > $PKG/etc/nsswitch.conf-incoming

# Build the package:
cd $PKG
tar czvf $TMP/etc.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $PKG
fi
