#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-jed

cd $TMP
tar xyvf $CWD/jed-B0.99-12.tar.bz2
cd jed-B0.99-12
zcat $CWD/jed-B0.99-12.diff.gz | patch -p1 --verbose --backup -z .orig
CFLAGS=-O2 JED_ROOT=/usr/lib/jed ./configure --prefix=/usr
make clean
make

mkdir -p $PKG/usr/doc $PKG/usr/bin $PKG/usr/lib/jed

cp -a src/objs/jed src/objs/rgrep $PKG/usr/bin
( cd $PKG/usr/doc ; rm -f jed-B0.99-12 )
( cd $PKG/usr/doc ; ln -sf /usr/lib/jed jed-B0.99-12 )
mkdir -p $PKG/usr/lib/jed
( cd $PKG/usr/lib/jed ; rm -rf info )
( cd $PKG/usr/lib/jed ; ln -sf /usr/info info )
cp -a COPYING COPYRIGHT INSTALL INSTALL.unx README changes.txt \
  $PKG/usr/lib/jed
cp -a bin doc lib $PKG/usr/lib/jed
chown -R root.root $PKG/usr/lib/jed
for file in info/jed* ; do
  cat $file | gzip -9c > $PKG/usr/$file.gz
done

cd $PKG
echo "y
n" | makepkg $TMP/jed.tgz
