#!/bin/sh
CWD=`pwd` 
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gnometop

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gtop-1.0.13.tar.gz
cd gtop-1.0.13
CFLAGS=-O2 ./configure --prefix=/opt/gnome \
	    --sysconfdir=/etc/opt/gnome \
            sparc-slackware-linux
make
make prefix=$PKG/opt/gnome sysconfdir=$PKG/etc/opt/gnome install
mkdir -p $PKG/usr/doc/gtop-1.0.13
cp -a ABOUT-NLS AUTHORS BUG-REPORTING COPYING ChangeLog INSTALL NEWS \
   README TODO $PKG/usr/doc/gtop-1.0.13
chown -R root.root $PKG/usr/doc/gtop-1.0.13

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gnometop.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gtop-1.0.13
  rm -rf $PKG
fi
