#!/bin/sh
cd $TMP
tar xvzf $CWD/portmap/portmap_4.tar.gz
cd portmap_4
zcat $CWD/portmap/portmap_4.diff.gz | patch -p1 --backup --suffix=.orig
make FACILITY=LOG_AUTH ZOMBIES='-DIGNORE_SIGCHLD -Dlint' LIBS="-lnsl"
