# HOW TO EDIT THIS FILE:
# The "handy ruler" below makes it easier to edit a package description.  Line
# up the first '|' above the ':' following the base package name, and the '|' on
# the right side marks the last column you can put a character in.  You must make
# exactly 11 lines for the formatting to be correct.  It's also customary to
# leave one space after the ':'.

    |-----handy-ruler------------------------------------------------------|
pine: pine (a menu driven mail client)
pine:
pine: A menu driven user mail program. Originally based on Elm (Pine Is
pine: No-longer Elm), but with many additional features that make it
pine: easier to use.  Also contains pilot (a simple file manager) and
pine: pico (an easy to use text editor).
pine:
pine:
pine:
pine:
pine:
