#!/bin/sh
# Set initial variables:
CWD=`pwd`

if [ "$TMP" = "" ]; then
  TMP=/tmp
fi

PKG=$TMP/package-zlib

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi


cd $TMP
tar xzvf $CWD/zlib-1.1.3.tar.gz
cd zlib-1.1.3
zcat $CWD/zlib-1.1.3-glibc.patch | patch -p1 -E
mkdir -p $PKG/usr/doc/zlib-1.1.3
cp -a ChangeLog FAQ INDEX README $PKG/usr/doc/zlib-1.1.3
chmod 644 $PKG/usr/doc/zlib-1.1.3/*
chown root.root $PKG/usr/doc/zlib-1.1.3/*
mkdir -p $PKG/usr/include
./configure --prefix=/usr
make clean
make
make install prefix=$PKG/usr
./configure --prefix=/usr --shared
make clean
make
make install prefix=$PKG/usr

cd $PKG
echo "y
n" | makepkg $TMP/zlib.tgz

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/zlib-1.1.3
  rm -rf $PKG
fi
