( cd usr/share/texmf/doc/fonts/marvosym ; rm -rf astro.README )
( cd usr/share/texmf/doc/fonts/marvosym ; ln -sf README.1st astro.README )
( cd usr/share/texmf/doc/fonts/marvosym ; rm -rf euro.README )
( cd usr/share/texmf/doc/fonts/marvosym ; ln -sf README.1st euro.README )
( cd usr/share/texmf/doc/help/faq/uktug-faq ; rm -rf index.html )
( cd usr/share/texmf/doc/help/faq/uktug-faq ; ln -sf texfaq_toc.html index.html )
( cd usr/share/texmf/doc ; rm -rf index.html )
( cd usr/share/texmf/doc ; ln -sf newhelpindex.html index.html )
( cd usr/doc ; rm -rf teTeX-1.0.7 )
( cd usr/doc ; ln -sf /usr/share/texmf/doc teTeX-1.0.7 )
