#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-reiserfs

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_reiserfs.tar.gz

echo "+======================+"
echo "| reiserfsprogs-3.x.0j |"
echo "+======================+"
cd $TMP
tar xzvf $CWD/reiserfsprogs-3.x.0j.tar.gz
cd reiserfsprogs-3.x.0j
CFLAGS=-O2 ./configure --prefix=/usr sparc-slackware-linux
make
strip debugreiserfs/debugreiserfs debugreiserfs/unpack
cat debugreiserfs/debugreiserfs > $PKG/sbin/debugreiserfs
cat debugreiserfs/unpack > $PKG/sbin/unpack
mkdir -p $PKG/usr/man/man8
cat debugreiserfs/debugreiserfs.8 | gzip -9c > $PKG/usr/man/man8/debugreiserfs.8.gz
strip fsck/reiserfsck
cat fsck/reiserfsck > $PKG/sbin/reiserfsck
cat fsck/reiserfsck.8 | gzip -9c > $PKG/usr/man/man8/reiserfsck.8.gz
strip mkreiserfs/mkreiserfs
cat mkreiserfs/mkreiserfs > $PKG/sbin/mkreiserfs
cat mkreiserfs/mkreiserfs.8 | gzip -9c > $PKG/usr/man/man8/mkreiserfs.8.gz
strip resize_reiserfs/resize_reiserfs
cat resize_reiserfs/resize_reiserfs > $PKG/sbin/resize_reiserfs
cat resize_reiserfs/resize_reiserfs.8 | gzip -9c > $PKG/usr/man/man8/resize_reiserfs.8.gz
mkdir -p $PKG/usr/doc/reiserfsprogs-3.x.0j
cp -a AUTHORS COPYING INSTALL NEWS README $PKG/usr/doc/reiserfsprogs-3.x.0j
chown root.root $PKG/usr/doc/reiserfsprogs-3.x.0j/*
chmod 644 $PKG/usr/doc/reiserfsprogs-3.x.0j/*

# Build the package:
cd $PKG
tar czvf $TMP/reiserfs.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/reiserfsprogs-3.x.0j
  rm -rf $PKG
fi
