( cd usr/bin ; rm -rf cc64 )
( cd usr/bin ; ln -sf gcc64 cc64 )
( cd usr/bin ; rm -rf egcs64 )
( cd usr/bin ; ln -sf egcs-2.92.11 egcs64 )
( cd usr/bin ; rm -rf gcc64 )
( cd usr/bin ; ln -sf egcs-2.92.11 gcc64 )
( cd usr/bin ; rm -rf sparc64-linux-gcc )
( cd usr/bin ; ln -sf egcs-2.92.11 sparc64-linux-gcc )
( cd usr/bin ; rm -rf sparc64-slackware-linux-gcc )
( cd usr/bin ; ln -sf egcs-2.92.11 sparc64-slackware-linux-gcc )
