#!/bin/sh
CWD=`pwd` 
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gnoaudio

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gnome-audio-1.4.0.tar.gz
( cd gnome-audio-1.4.0/sounds
  make CFLAGS=-O2 prefix=/opt/gnome
  make CFLAGS=-O2 prefix=$PKG/opt/gnome install
)
mkdir -p $PKG/usr/doc/gnome-audio-1.4.0
cp -a README $PKG/usr/doc/gnome-audio-1.4.0
chown -R root.root $PKG/usr/doc/gnome-audio-1.4.0

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gnoaudio.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnome-audio-1.4.0
  rm -rf $PKG
fi
