#!/bin/sh
CWD=`pwd`
TMP=/tmp
PKG=$TMP/package-isapnptools
rm -rf $PKG
mkdir -p $PKG
cd $TMP

VERSION=1.26
ARCH=i386
BUILD=1

tar xzvf $CWD/isapnptools-$VERSION.tar.gz
cd isapnptools-$VERSION

./configure --prefix=/usr
make
( cd src
  strip isapnp pnpdump
  mkdir -p $PKG/sbin
  cat isapnp > $PKG/sbin/isapnp
  cat pnpdump > $PKG/sbin/pnpdump
  chown -R root.bin $PKG/sbin
  chmod 755 $PKG/sbin/* )
mkdir -p $PKG/etc
( cd etc
  mkdir -p $PKG/etc
  cat isapnp.conf > $PKG/etc/isapnp.conf.sample
  cat isapnp.gone > $PKG/etc/isapnp.gone.sample )
( cd doc
  mkdir -p $PKG/usr/man/man5
  cat isapnp.conf.5 | gzip -9c > $PKG/usr/man/man5/isapnp.conf.5.gz
  mkdir -p $PKG/usr/man/man8
  cat isapnp.8 | gzip -9c > $PKG/usr/man/man8/isapnp.8.gz
  cat pnpdump.8 | gzip -9c > $PKG/usr/man/man8/pnpdump.8.gz ) 
mkdir -p $PKG/usr/doc/isapnptools-$VERSION
cp -a AUTHORS CHANGES COPYING INSTALL README isapnp.lsm doc/isapnpfaq.txt doc/README.ide doc/README.initrd $PKG/usr/doc/isapnptools-$VERSION
chown -R root.root $PKG/usr/doc/isapnptools-$VERSION
chmod 644 $PKG/usr/doc/isapnptools-$VERSION/*
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Build the package:
cd $PKG
echo "n" | makepkg $TMP/isapnptools-$VERSION-$ARCH-$BUILD.tgz


