#!/bin/sh
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gtkplus

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gtk+-1.2.10.tar.gz
cd gtk+-1.2.10
./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            --with-glib-prefix=/opt/gnome \
            sparc-slackware-linux
make CFLAGS=-O2
make CFLAGS=-O2 DESTDIR=$PKG install
gzip -9 $PKG/opt/gnome/man/man1/*
mkdir -p $PKG/usr/doc/gtk+-1.2.10
cp -a ABOUT-NLS AUTHORS COPYING HACKING INSTALL \
  NEWS README README.cvs-commits TODO $PKG/usr/doc/gtk+-1.2.10
chown -R root.root $PKG/usr/doc/gtk+-1.2.10

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gtk+.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/
  rm -rf $PKG/gtk+-1.2.10
fi
