#!/bin/sh
CWD=`pwd`
TMP=${TMP:-/tmp}
PKG=$TMP/package-gkrellm

VERSION=2.2.9
PKGVER=2.2.9
ARCH=${ARCH:-i486}
BUILD=1

rm -rf $PKG
mkdir -p $PKG
cd $TMP
rm -rf gkrellm-$VERSION
tar xjvf $CWD/gkrellm-$VERSION.tar.bz2
cd gkrellm-$VERSION
# Increase the default width slightly, and don't use the text
# shadow effect by default (this seems better with Pango font
# rendering):
zcat $CWD/gkrellm.theme.defaults.diff.gz | patch -p1 --verbose || exit 1
chown -R root:root .
find . -perm 777 -exec chmod 755 {} \;
find . -perm 664 -exec chmod 644 {} \;
make \
  INSTALLDIR=/usr/bin \
  INCLUDEDIR=/usr/include \
  MANDIR=/usr/man/man1 \
  LOCALEDIR=/usr/share/locale \
  PKGCONFIGDIR=/usr/lib/pkgconfig

# We will need this installed to build plugins, so...
make install

# Install to the $PKG dir:
make install \
  INSTALLDIR=$PKG/usr/bin \
  INCLUDEDIR=$PKG/usr/include \
  MANDIR=$PKG/usr/man/man1 \
  LOCALEDIR=$PKG/usr/share/locale \
  PKGCONFIGDIR=$PKG/usr/lib/pkgconfig
mkdir -p $PKG/usr/lib/gkrellm2/plugins
mkdir -p $PKG/usr/doc/gkrellm-$VERSION
cp -a \
  COPYRIGHT CREDITS INSTALL README Themes.html \
  $PKG/usr/doc/gkrellm-$VERSION
gzip -9 $PKG/usr/man/man?/*.?
mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

# Add optional plugin(s):
# The countdown plugin is needed to track X-Day.  ;-)
COUNTDOWN=0.1.1
cd $TMP
rm -rf gkrellm-countdown
tar xzf $CWD/gkrellm-countdown-$COUNTDOWN.tar.gz
cd gkrellm-countdown
chown -R root:root .
make
cp gkrellm-countdown.so $PKG/usr/lib/gkrellm2/plugins
mkdir -p $PKG/usr/doc/gkrellm-countdown-$COUNTDOWN
cp -a \
  COPYING ChangeLog README \
  $PKG/usr/doc/gkrellm-countdown-$COUNTDOWN

# Strip binaries:
( cd $PKG
  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null
)

cd $PKG
makepkg -l y -c n ../gkrellm-$PKGVER-$ARCH-$BUILD.tgz

