#!/bin/sh
# Set initial variables:
CWD=`pwd`
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-devfsd

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

# Explode the package framework:
cd $PKG
explodepkg $CWD/_devfsd.tgz

echo "+================+"
echo "| devfsd-v1.3.11 |"
echo "+================+"
cd $TMP
tar xzvf $CWD/devfsd-v1.3.11.tar.gz
cd devfsd
make
strip devfsd
cat devfsd > $PKG/sbin/devfsd
cat devfsd.conf > $PKG/etc/devfsd.conf.new
cat modules.devfs > $PKG/etc/modules.devfs
cat devfsd.8 | gzip -9c > $PKG/usr/man/man8/devfsd.8.gz
mkdir -p $PKG/usr/doc/devfsd-v1.3.11
( cd $PKG/usr/doc/devfsd-v1.3.11 ; wget http://www.atnf.csiro.au/~rgooch/linux/docs/devfs.html )

# Build the package:
cd $PKG
tar czvf $TMP/devfsd.tgz .

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/devfsd-v1.3.11
  rm -rf $PKG
fi
