#!/bin/sh
CWD=`pwd` 
if [ "$TMP" = "" ]; then
  TMP=/tmp
fi
PKG=$TMP/package-gnomepim

if [ ! -d $TMP ]; then
  mkdir -p $TMP # location to build the source
fi
if [ ! -d $PKG ]; then
  mkdir -p $PKG # place for the package to be built
fi

cd $TMP
tar xzvf $CWD/gnome-pim-1.4.0.tar.gz
cd gnome-pim-1.4.0
CFLAGS=-O2 ./configure --prefix=/opt/gnome \
            --sysconfdir=/etc/opt/gnome \
            --localstatedir=/var/lib \
            sparc-slackware-linux
make
make DESTDIR=$PKG install
mkdir -p $PKG/usr/doc/gnome-pim-1.4.0
cp -a ABOUT-NLS AUTHORS COPYING ChangeLog INSTALL NEWS README \
   $PKG/usr/doc/gnome-pim-1.4.0
chown -R root.root $PKG/usr/doc/gnome-pim-1.4.0

# Build the package:
cd $PKG
echo "y
n" | makepkg $TMP/gnomepim.tgz

# Warn of zero-length files:
for file in `find . -type f -print` ; do
 if [ "`filesize $file`" = "0" ]; then
  echo "WARNING: zero length file $file"
 fi
 if [ "`filesize $file`" = "20" ]; then
  echo "WARNING: possible empty gzipped file $file"
 fi
done

# Clean up the extra stuff:
if [ "$1" = "--cleanup" ]; then
  rm -rf $TMP/gnome-pim-1.4.0
  rm -rf $PKG
fi
